import { execSync } from 'node:child_process';
import fs from 'node:fs';

function sh(cmd) {
	console.log(`\n$ ${cmd}`);
	execSync(cmd, { stdio: 'inherit' });
}

function getPkg() {
	return JSON.parse(fs.readFileSync('package.json', 'utf8'));
}

const pkg = getPkg();
const version = pkg.version;
const tag = `v${version}`;

const title = process.argv[2] ?? `${pkg.displayName || pkg.name} ${tag}`;
const notesFile = process.argv[3]; // optional path to release notes

// checks
try {
	execSync('gh --version', { stdio: 'ignore' });
} catch {
	console.error('❌ GitHub CLI (gh) not found. Install it or use a GitHub Action.');
	process.exit(1);
}

sh('git status --porcelain');
const dirty = execSync('git status --porcelain', { encoding: 'utf8' }).trim();
if (dirty) {
	console.error('❌ Working tree is dirty. Commit your changes before releasing.');
	process.exit(1);
}

// find created vsix (vsce names it like publisher.extension-0.1.0.vsix)
const vsix = fs
	.readdirSync('./dist')
	.filter((f) => f.endsWith('.vsix'))
	.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs)[0];

if (!vsix) {
	console.error('❌ No .vsix found after build.');
	process.exit(1);
}

// tag + push
sh(`git tag ${tag}`);
sh('git push');
sh(`git push origin ${tag}`);

// release notes
let notesArg = '';
if (notesFile) {
	if (!fs.existsSync(notesFile)) {
		console.error(`❌ Notes file not found: ${notesFile}`);
		process.exit(1);
	}
	notesArg = `--notes-file "${notesFile}"`;
} else {
	// fallback to autogenerated notes
	notesArg = '--generate-notes';
}

// create release + upload asset
sh(`gh release create ${tag} "${vsix}" --title "${title}" ${notesArg}`);

console.log(`✅ Released ${tag} with asset ${vsix}`);
